//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffLoans.FinService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transactions", Namespace="http://schemas.datacontract.org/2004/07/FinServiceSassa")]
    [System.SerializableAttribute()]
    public partial class Transactions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StaffLoans.FinService.AirtimeTransaction[] AirtimeTransField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StaffLoans.FinService.ElectricityTransaction[] ElectricityTransField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StaffLoans.FinService.AirtimeTransaction[] AirtimeTrans {
            get {
                return this.AirtimeTransField;
            }
            set {
                if ((object.ReferenceEquals(this.AirtimeTransField, value) != true)) {
                    this.AirtimeTransField = value;
                    this.RaisePropertyChanged("AirtimeTrans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StaffLoans.FinService.ElectricityTransaction[] ElectricityTrans {
            get {
                return this.ElectricityTransField;
            }
            set {
                if ((object.ReferenceEquals(this.ElectricityTransField, value) != true)) {
                    this.ElectricityTransField = value;
                    this.RaisePropertyChanged("ElectricityTrans");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AirtimeTransaction", Namespace="http://schemas.datacontract.org/2004/07/FinServiceSassa")]
    [System.SerializableAttribute()]
    public partial class AirtimeTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellNumber {
            get {
                return this.CellNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CellNumberField, value) != true)) {
                    this.CellNumberField = value;
                    this.RaisePropertyChanged("CellNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeField, value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDateTime {
            get {
                return this.TransactionDateTimeField;
            }
            set {
                if ((this.TransactionDateTimeField.Equals(value) != true)) {
                    this.TransactionDateTimeField = value;
                    this.RaisePropertyChanged("TransactionDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElectricityTransaction", Namespace="http://schemas.datacontract.org/2004/07/FinServiceSassa")]
    [System.SerializableAttribute()]
    public partial class ElectricityTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellNumber {
            get {
                return this.CellNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CellNumberField, value) != true)) {
                    this.CellNumberField = value;
                    this.RaisePropertyChanged("CellNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterNo {
            get {
                return this.MeterNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNoField, value) != true)) {
                    this.MeterNoField = value;
                    this.RaisePropertyChanged("MeterNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeField, value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDateTime {
            get {
                return this.TransactionDateTimeField;
            }
            set {
                if ((this.TransactionDateTimeField.Equals(value) != true)) {
                    this.TransactionDateTimeField = value;
                    this.RaisePropertyChanged("TransactionDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipients", Namespace="http://schemas.datacontract.org/2004/07/FinServiceSassa")]
    [System.SerializableAttribute()]
    public partial class Recipients : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RecipientField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Recipient {
            get {
                return this.RecipientField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientField, value) != true)) {
                    this.RecipientField = value;
                    this.RaisePropertyChanged("Recipient");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Historicaltransactions", Namespace="http://schemas.datacontract.org/2004/07/FinServiceSassa")]
    [System.SerializableAttribute()]
    public partial class Historicaltransactions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StaffLoans.FinService.HistoricalTransaction[] HistTransactionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StaffLoans.FinService.HistoricalTransaction[] HistTransaction {
            get {
                return this.HistTransactionField;
            }
            set {
                if ((object.ReferenceEquals(this.HistTransactionField, value) != true)) {
                    this.HistTransactionField = value;
                    this.RaisePropertyChanged("HistTransaction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoricalTransaction", Namespace="http://schemas.datacontract.org/2004/07/FinServiceSassa")]
    [System.SerializableAttribute()]
    public partial class HistoricalTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstRegCellNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellNo {
            get {
                return this.CellNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CellNoField, value) != true)) {
                    this.CellNoField = value;
                    this.RaisePropertyChanged("CellNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstRegCellNo {
            get {
                return this.FirstRegCellNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstRegCellNoField, value) != true)) {
                    this.FirstRegCellNoField = value;
                    this.RaisePropertyChanged("FirstRegCellNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDNumber {
            get {
                return this.IDNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IDNumberField, value) != true)) {
                    this.IDNumberField = value;
                    this.RaisePropertyChanged("IDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterNo {
            get {
                return this.MeterNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNoField, value) != true)) {
                    this.MeterNoField = value;
                    this.RaisePropertyChanged("MeterNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Month {
            get {
                return this.MonthField;
            }
            set {
                if ((object.ReferenceEquals(this.MonthField, value) != true)) {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegMethod {
            get {
                return this.RegMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.RegMethodField, value) != true)) {
                    this.RegMethodField = value;
                    this.RaisePropertyChanged("RegMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationRowList", Namespace="http://schemas.datacontract.org/2004/07/FinServiceSassa")]
    [System.SerializableAttribute()]
    public partial class RegistrationRowList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StaffLoans.FinService.RegistrationRow[] RegistrationListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StaffLoans.FinService.RegistrationRow[] RegistrationList {
            get {
                return this.RegistrationListField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationListField, value) != true)) {
                    this.RegistrationListField = value;
                    this.RaisePropertyChanged("RegistrationList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationRow", Namespace="http://schemas.datacontract.org/2004/07/FinServiceSassa")]
    [System.SerializableAttribute()]
    public partial class RegistrationRow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlockedIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlockedMSISDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDBlackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSISDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSISDNBlackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistrationDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlockedID {
            get {
                return this.BlockedIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockedIDField, value) != true)) {
                    this.BlockedIDField = value;
                    this.RaisePropertyChanged("BlockedID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlockedMSISDN {
            get {
                return this.BlockedMSISDNField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockedMSISDNField, value) != true)) {
                    this.BlockedMSISDNField = value;
                    this.RaisePropertyChanged("BlockedMSISDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDBlack {
            get {
                return this.IDBlackField;
            }
            set {
                if ((object.ReferenceEquals(this.IDBlackField, value) != true)) {
                    this.IDBlackField = value;
                    this.RaisePropertyChanged("IDBlack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDNumber {
            get {
                return this.IDNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IDNumberField, value) != true)) {
                    this.IDNumberField = value;
                    this.RaisePropertyChanged("IDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSISDN {
            get {
                return this.MSISDNField;
            }
            set {
                if ((object.ReferenceEquals(this.MSISDNField, value) != true)) {
                    this.MSISDNField = value;
                    this.RaisePropertyChanged("MSISDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSISDNBlack {
            get {
                return this.MSISDNBlackField;
            }
            set {
                if ((object.ReferenceEquals(this.MSISDNBlackField, value) != true)) {
                    this.MSISDNBlackField = value;
                    this.RaisePropertyChanged("MSISDNBlack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDateTime {
            get {
                return this.RegistrationDateTimeField;
            }
            set {
                if ((this.RegistrationDateTimeField.Equals(value) != true)) {
                    this.RegistrationDateTimeField = value;
                    this.RaisePropertyChanged("RegistrationDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountSummary", Namespace="http://schemas.datacontract.org/2004/07/FinServiceSassa")]
    [System.SerializableAttribute()]
    public partial class AccountSummary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BlacklistDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LinkedLastMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LinkedTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistrationDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BlacklistDate {
            get {
                return this.BlacklistDateField;
            }
            set {
                if ((this.BlacklistDateField.Equals(value) != true)) {
                    this.BlacklistDateField = value;
                    this.RaisePropertyChanged("BlacklistDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LinkedLastMonth {
            get {
                return this.LinkedLastMonthField;
            }
            set {
                if ((this.LinkedLastMonthField.Equals(value) != true)) {
                    this.LinkedLastMonthField = value;
                    this.RaisePropertyChanged("LinkedLastMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LinkedTotal {
            get {
                return this.LinkedTotalField;
            }
            set {
                if ((this.LinkedTotalField.Equals(value) != true)) {
                    this.LinkedTotalField = value;
                    this.RaisePropertyChanged("LinkedTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDateTime {
            get {
                return this.RegistrationDateTimeField;
            }
            set {
                if ((this.RegistrationDateTimeField.Equals(value) != true)) {
                    this.RegistrationDateTimeField = value;
                    this.RaisePropertyChanged("RegistrationDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationType {
            get {
                return this.RegistrationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationTypeField, value) != true)) {
                    this.RegistrationTypeField = value;
                    this.RaisePropertyChanged("RegistrationType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MSISDNDetails", Namespace="http://schemas.datacontract.org/2004/07/FinServiceSassa")]
    [System.SerializableAttribute()]
    public partial class MSISDNDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDLinkedsLastMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDLinkedsTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDLinkedsLastMonth {
            get {
                return this.IDLinkedsLastMonthField;
            }
            set {
                if ((this.IDLinkedsLastMonthField.Equals(value) != true)) {
                    this.IDLinkedsLastMonthField = value;
                    this.RaisePropertyChanged("IDLinkedsLastMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDLinkedsTotal {
            get {
                return this.IDLinkedsTotalField;
            }
            set {
                if ((this.IDLinkedsTotalField.Equals(value) != true)) {
                    this.IDLinkedsTotalField = value;
                    this.RaisePropertyChanged("IDLinkedsTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinService.IFinService")]
    public interface IFinService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/GetUSN", ReplyAction="http://tempuri.org/IFinService/GetUSNResponse")]
        string GetUSN(string IDNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/GetUSN", ReplyAction="http://tempuri.org/IFinService/GetUSNResponse")]
        System.Threading.Tasks.Task<string> GetUSNAsync(string IDNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/GetTransactionHistory", ReplyAction="http://tempuri.org/IFinService/GetTransactionHistoryResponse")]
        StaffLoans.FinService.Transactions GetTransactionHistory(string IDNumber, System.DateTime dtFrom, System.DateTime dtTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/GetTransactionHistory", ReplyAction="http://tempuri.org/IFinService/GetTransactionHistoryResponse")]
        System.Threading.Tasks.Task<StaffLoans.FinService.Transactions> GetTransactionHistoryAsync(string IDNumber, System.DateTime dtFrom, System.DateTime dtTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/SendSMS", ReplyAction="http://tempuri.org/IFinService/SendSMSResponse")]
        void SendSMS(string MSISDN, string MessageText, string Source);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/SendSMS", ReplyAction="http://tempuri.org/IFinService/SendSMSResponse")]
        System.Threading.Tasks.Task SendSMSAsync(string MSISDN, string MessageText, string Source);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/SendEmail", ReplyAction="http://tempuri.org/IFinService/SendEmailResponse")]
        void SendEmail(StaffLoans.FinService.Recipients recipients, string fromaddress, string Body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/SendEmail", ReplyAction="http://tempuri.org/IFinService/SendEmailResponse")]
        System.Threading.Tasks.Task SendEmailAsync(StaffLoans.FinService.Recipients recipients, string fromaddress, string Body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/LoadBlacklistIntoTemp", ReplyAction="http://tempuri.org/IFinService/LoadBlacklistIntoTempResponse")]
        StaffLoans.FinService.LoadBlacklistIntoTempResponse LoadBlacklistIntoTemp(StaffLoans.FinService.LoadBlacklistIntoTempRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/LoadBlacklistIntoTemp", ReplyAction="http://tempuri.org/IFinService/LoadBlacklistIntoTempResponse")]
        System.Threading.Tasks.Task<StaffLoans.FinService.LoadBlacklistIntoTempResponse> LoadBlacklistIntoTempAsync(StaffLoans.FinService.LoadBlacklistIntoTempRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/BulkRegistrationCheck", ReplyAction="http://tempuri.org/IFinService/BulkRegistrationCheckResponse")]
        StaffLoans.FinService.RegistrationRowList BulkRegistrationCheck(string username, string filename, string[] lstID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/BulkRegistrationCheck", ReplyAction="http://tempuri.org/IFinService/BulkRegistrationCheckResponse")]
        System.Threading.Tasks.Task<StaffLoans.FinService.RegistrationRowList> BulkRegistrationCheckAsync(string username, string filename, string[] lstID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/GetAccountSummary", ReplyAction="http://tempuri.org/IFinService/GetAccountSummaryResponse")]
        StaffLoans.FinService.AccountSummary GetAccountSummary(string IDNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/GetAccountSummary", ReplyAction="http://tempuri.org/IFinService/GetAccountSummaryResponse")]
        System.Threading.Tasks.Task<StaffLoans.FinService.AccountSummary> GetAccountSummaryAsync(string IDNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/GetMSISDNDetail", ReplyAction="http://tempuri.org/IFinService/GetMSISDNDetailResponse")]
        StaffLoans.FinService.MSISDNDetails GetMSISDNDetail(string MSISDN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/GetMSISDNDetail", ReplyAction="http://tempuri.org/IFinService/GetMSISDNDetailResponse")]
        System.Threading.Tasks.Task<StaffLoans.FinService.MSISDNDetails> GetMSISDNDetailAsync(string MSISDN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/ValidateUser", ReplyAction="http://tempuri.org/IFinService/ValidateUserResponse")]
        bool ValidateUser(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinService/ValidateUser", ReplyAction="http://tempuri.org/IFinService/ValidateUserResponse")]
        System.Threading.Tasks.Task<bool> ValidateUserAsync(string Username);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadBlacklistIntoTemp", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadBlacklistIntoTempRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool Blacklist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string extractType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string filename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Reason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string[] lstID;
        
        public LoadBlacklistIntoTempRequest() {
        }
        
        public LoadBlacklistIntoTempRequest(string username, bool Blacklist, string extractType, string filename, string Reason, string[] lstID) {
            this.username = username;
            this.Blacklist = Blacklist;
            this.extractType = extractType;
            this.filename = filename;
            this.Reason = Reason;
            this.lstID = lstID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadBlacklistIntoTempResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadBlacklistIntoTempResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StaffLoans.FinService.Historicaltransactions LoadBlacklistIntoTempResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int FileID;
        
        public LoadBlacklistIntoTempResponse() {
        }
        
        public LoadBlacklistIntoTempResponse(StaffLoans.FinService.Historicaltransactions LoadBlacklistIntoTempResult, int FileID) {
            this.LoadBlacklistIntoTempResult = LoadBlacklistIntoTempResult;
            this.FileID = FileID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinServiceChannel : StaffLoans.FinService.IFinService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinServiceClient : System.ServiceModel.ClientBase<StaffLoans.FinService.IFinService>, StaffLoans.FinService.IFinService {
        
        public FinServiceClient() {
        }
        
        public FinServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetUSN(string IDNumber) {
            return base.Channel.GetUSN(IDNumber);
        }
        
        public System.Threading.Tasks.Task<string> GetUSNAsync(string IDNumber) {
            return base.Channel.GetUSNAsync(IDNumber);
        }
        
        public StaffLoans.FinService.Transactions GetTransactionHistory(string IDNumber, System.DateTime dtFrom, System.DateTime dtTo) {
            return base.Channel.GetTransactionHistory(IDNumber, dtFrom, dtTo);
        }
        
        public System.Threading.Tasks.Task<StaffLoans.FinService.Transactions> GetTransactionHistoryAsync(string IDNumber, System.DateTime dtFrom, System.DateTime dtTo) {
            return base.Channel.GetTransactionHistoryAsync(IDNumber, dtFrom, dtTo);
        }
        
        public void SendSMS(string MSISDN, string MessageText, string Source) {
            base.Channel.SendSMS(MSISDN, MessageText, Source);
        }
        
        public System.Threading.Tasks.Task SendSMSAsync(string MSISDN, string MessageText, string Source) {
            return base.Channel.SendSMSAsync(MSISDN, MessageText, Source);
        }
        
        public void SendEmail(StaffLoans.FinService.Recipients recipients, string fromaddress, string Body) {
            base.Channel.SendEmail(recipients, fromaddress, Body);
        }
        
        public System.Threading.Tasks.Task SendEmailAsync(StaffLoans.FinService.Recipients recipients, string fromaddress, string Body) {
            return base.Channel.SendEmailAsync(recipients, fromaddress, Body);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StaffLoans.FinService.LoadBlacklistIntoTempResponse StaffLoans.FinService.IFinService.LoadBlacklistIntoTemp(StaffLoans.FinService.LoadBlacklistIntoTempRequest request) {
            return base.Channel.LoadBlacklistIntoTemp(request);
        }
        
        public StaffLoans.FinService.Historicaltransactions LoadBlacklistIntoTemp(string username, bool Blacklist, string extractType, string filename, string Reason, string[] lstID, out int FileID) {
            StaffLoans.FinService.LoadBlacklistIntoTempRequest inValue = new StaffLoans.FinService.LoadBlacklistIntoTempRequest();
            inValue.username = username;
            inValue.Blacklist = Blacklist;
            inValue.extractType = extractType;
            inValue.filename = filename;
            inValue.Reason = Reason;
            inValue.lstID = lstID;
            StaffLoans.FinService.LoadBlacklistIntoTempResponse retVal = ((StaffLoans.FinService.IFinService)(this)).LoadBlacklistIntoTemp(inValue);
            FileID = retVal.FileID;
            return retVal.LoadBlacklistIntoTempResult;
        }
        
        public System.Threading.Tasks.Task<StaffLoans.FinService.LoadBlacklistIntoTempResponse> LoadBlacklistIntoTempAsync(StaffLoans.FinService.LoadBlacklistIntoTempRequest request) {
            return base.Channel.LoadBlacklistIntoTempAsync(request);
        }
        
        public StaffLoans.FinService.RegistrationRowList BulkRegistrationCheck(string username, string filename, string[] lstID) {
            return base.Channel.BulkRegistrationCheck(username, filename, lstID);
        }
        
        public System.Threading.Tasks.Task<StaffLoans.FinService.RegistrationRowList> BulkRegistrationCheckAsync(string username, string filename, string[] lstID) {
            return base.Channel.BulkRegistrationCheckAsync(username, filename, lstID);
        }
        
        public StaffLoans.FinService.AccountSummary GetAccountSummary(string IDNumber) {
            return base.Channel.GetAccountSummary(IDNumber);
        }
        
        public System.Threading.Tasks.Task<StaffLoans.FinService.AccountSummary> GetAccountSummaryAsync(string IDNumber) {
            return base.Channel.GetAccountSummaryAsync(IDNumber);
        }
        
        public StaffLoans.FinService.MSISDNDetails GetMSISDNDetail(string MSISDN) {
            return base.Channel.GetMSISDNDetail(MSISDN);
        }
        
        public System.Threading.Tasks.Task<StaffLoans.FinService.MSISDNDetails> GetMSISDNDetailAsync(string MSISDN) {
            return base.Channel.GetMSISDNDetailAsync(MSISDN);
        }
        
        public bool ValidateUser(string Username) {
            return base.Channel.ValidateUser(Username);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateUserAsync(string Username) {
            return base.Channel.ValidateUserAsync(Username);
        }
    }
}
